#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
ENV_FILE="${PYBT_ENV_FILE:-${HOME}/.pybt/.env.realtime}"
TEMPLATE_USER_CFG="${REPO_ROOT}/examples/user_env_config.jsonc"
DEFAULT_RUN_CONFIG="${REPO_ROOT}/configs/profiles/sina_hq_api_live.jsonc"

DETACH=1
RUN_CONFIG="${RUN_CONFIG:-}"
PERSIST_ENV=1

usage() {
  cat <<EOF
Usage: bash scripts/start_local_app.sh [options]

交互式启动本机完整应用（server + bot）。
当关键配置缺失时，会在启动前提示输入。

Options:
  --foreground           前台运行（默认后台 --detach）
  --detach               后台运行
  --run-config PATH      启动后自动提交配置并启动一次 run
  --no-persist           不把输入内容保存到 ${HOME}/.pybt/.env.realtime
  --help                 显示帮助

Tips:
  - 会优先读取 ${ENV_FILE}
  - 若 ~/.pybt/config.jsonc 不存在，会自动从 examples 模板创建
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --foreground)
      DETACH=0
      shift
      ;;
    --detach)
      DETACH=1
      shift
      ;;
    --run-config)
      if [[ $# -lt 2 ]]; then
        echo "--run-config requires a value" >&2
        exit 1
      fi
      RUN_CONFIG="$2"
      shift 2
      ;;
    --no-persist)
      PERSIST_ENV=0
      shift
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ ! -f "${ENV_FILE}" && -f "${REPO_ROOT}/.env.realtime" ]]; then
  mkdir -p "$(dirname "${ENV_FILE}")"
  cp "${REPO_ROOT}/.env.realtime" "${ENV_FILE}"
  chmod 600 "${ENV_FILE}" || true
  echo "已迁移 ${REPO_ROOT}/.env.realtime -> ${ENV_FILE}"
fi

if [[ -f "${ENV_FILE}" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "${ENV_FILE}"
  set +a
fi

prompted=0

prompt_if_empty() {
  local var_name="$1"
  local prompt_text="$2"
  local is_secret="${3:-0}"
  local current="${!var_name:-}"

  if [[ -n "${current}" ]]; then
    return 0
  fi
  if [[ ! -t 0 ]]; then
    echo "Missing ${var_name} and no TTY available for prompt." >&2
    exit 1
  fi

  while true; do
    if [[ "${is_secret}" == "1" ]]; then
      read -r -s -p "${prompt_text}: " current
      echo
    else
      read -r -p "${prompt_text}: " current
    fi
    if [[ -n "${current}" ]]; then
      printf -v "${var_name}" "%s" "${current}"
      export "${var_name}"
      prompted=$((prompted + 1))
      return 0
    fi
    echo "输入不能为空，请重试。"
  done
}

prompt_with_default() {
  local var_name="$1"
  local prompt_text="$2"
  local default_value="$3"
  local current="${!var_name:-}"
  local input=""

  if [[ -n "${current}" ]]; then
    return 0
  fi
  if [[ ! -t 0 ]]; then
    printf -v "${var_name}" "%s" "${default_value}"
    export "${var_name}"
    return 0
  fi

  read -r -p "${prompt_text} [${default_value}]: " input
  current="${input:-${default_value}}"
  printf -v "${var_name}" "%s" "${current}"
  export "${var_name}"
  prompted=$((prompted + 1))
}

ensure_user_config() {
  local target="${HOME}/.pybt/config.jsonc"
  if [[ -f "${target}" ]]; then
    return 0
  fi
  mkdir -p "${HOME}/.pybt"
  if [[ -f "${TEMPLATE_USER_CFG}" ]]; then
    cp "${TEMPLATE_USER_CFG}" "${target}"
    chmod 600 "${target}" || true
    echo "已创建用户敏感配置模板: ${target}"
    echo "请按需编辑 token/headers 后再用于生产。"
  else
    cat >"${target}" <<'EOF'
{
  "secrets": {
    "eastmoney": {
      "token": "",
      "headers": {},
      "snapshot_headers": {}
    },
    "sina": {
      "headers": {}
    }
  }
}
EOF
    chmod 600 "${target}" || true
  fi
}

save_env_file() {
  mkdir -p "$(dirname "${ENV_FILE}")"
  umask 077
  {
    echo "# Auto-generated by scripts/start_local_app.sh"
    printf "PYBT_API_KEY=%q\n" "${PYBT_API_KEY}"
    printf "TELEGRAM_BOT_TOKEN=%q\n" "${TELEGRAM_BOT_TOKEN}"
    printf "TELEGRAM_ADMIN_PASSWORD=%q\n" "${TELEGRAM_ADMIN_PASSWORD}"
    printf "PYBT_BASE_DIR=%q\n" "${PYBT_BASE_DIR}"
    printf "PYBT_SERVER_HOST=%q\n" "${PYBT_SERVER_HOST}"
    printf "PYBT_SERVER_PORT=%q\n" "${PYBT_SERVER_PORT}"
    printf "PYBT_SERVER_URL=%q\n" "${PYBT_SERVER_URL}"
    if [[ -n "${RUN_CONFIG}" ]]; then
      printf "RUN_CONFIG=%q\n" "${RUN_CONFIG}"
    fi
  } >"${ENV_FILE}"
  chmod 600 "${ENV_FILE}" || true
  echo "已保存启动配置到: ${ENV_FILE}"
}

prompt_if_empty PYBT_API_KEY "请输入 PYBT_API_KEY" 1
prompt_if_empty TELEGRAM_BOT_TOKEN "请输入 TELEGRAM_BOT_TOKEN" 1
prompt_if_empty TELEGRAM_ADMIN_PASSWORD "请输入 TELEGRAM_ADMIN_PASSWORD" 1
prompt_with_default PYBT_BASE_DIR "请输入 PYBT_BASE_DIR" "${HOME}/.pybt"
prompt_with_default PYBT_SERVER_HOST "请输入 PYBT_SERVER_HOST" "127.0.0.1"
prompt_with_default PYBT_SERVER_PORT "请输入 PYBT_SERVER_PORT" "8765"
prompt_with_default PYBT_SERVER_URL "请输入 PYBT_SERVER_URL" "http://${PYBT_SERVER_HOST}:${PYBT_SERVER_PORT}"

if [[ -z "${RUN_CONFIG}" && -t 0 ]]; then
  read -r -p "可选：自动启动 run 的配置文件路径（回车跳过） [${DEFAULT_RUN_CONFIG}]: " _run_input
  if [[ -n "${_run_input}" ]]; then
    RUN_CONFIG="${_run_input}"
    prompted=$((prompted + 1))
  fi
fi

if [[ -n "${RUN_CONFIG}" && ! -f "${RUN_CONFIG}" ]]; then
  echo "run 配置文件不存在: ${RUN_CONFIG}" >&2
  exit 1
fi

ensure_user_config

if (( PERSIST_ENV == 1 && prompted > 0 )); then
  if [[ -t 0 ]]; then
    read -r -p "是否保存本次输入到 ${ENV_FILE} 供下次复用？ [Y/n]: " yn
    yn="${yn:-Y}"
    if [[ "${yn}" =~ ^[Yy]$ ]]; then
      save_env_file
    fi
  else
    save_env_file
  fi
fi

export PYBT_API_KEY TELEGRAM_BOT_TOKEN TELEGRAM_ADMIN_PASSWORD
export PYBT_BASE_DIR PYBT_SERVER_HOST PYBT_SERVER_PORT PYBT_SERVER_URL

args=()
if (( DETACH == 1 )); then
  args+=(--detach)
fi
if [[ -n "${RUN_CONFIG}" ]]; then
  args+=(--run-config "${RUN_CONFIG}")
fi
args+=(--host "${PYBT_SERVER_HOST}" --port "${PYBT_SERVER_PORT}" --base-dir "${PYBT_BASE_DIR}")

exec bash "${REPO_ROOT}/scripts/start_realtime_system.sh" "${args[@]}"
